# Define the messages you want to broadcast.
messages:
 - 'juega tranquilo aqui tu felicidad es nuestra prioridad'
 - 'unete a nuestro dc'
 - 'invita a tus amigos para hacer crecer esta comunidad tan bonita'
 - 'diviertete sin toxicidad de nadie'

# Header & Footer
Header: "&8&m-+-----------------------------+-"
Footer: "&c&m-+-----------------------------+-" 
# The Broadcast Sound 
sound: CLICK
# No Permission Message
nopermissionmessage: &4You have no permission.
# Interval Between Broadcasts In Seconds
interval: 350
